[project]
name = "deno-clarigen"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "/Users/hankstoever/.clarinet/cache"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.tester]
path = "contracts/tester.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
