name: Changesets

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Changesets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 16.9.1
          cache: "yarn"

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          publish: echo "Yay!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
